# Generated by Django 4.0.6 on 2023-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANMAAACeCAMAAACfH89ZAAAAXVBMVEXDw8MAAADHx8ckJCSnp6e2tragoKAYGBhzc3PNzc3KysqsrKwVFRW+vr5HR0cODg4xMTFZWVmCgoKRkZFfX19CQkJRUVFsbGw5OTl6enqXl5ccHByJiYksLCxnZ2f9Hb2sAAAB9klEQVR4nO3a23KCMBRA0eRgEIIWFVq0t///zCKxqEBb8EWO3eutFWayB0O4aAwAAAAAAAAAAAAAAAAAAAAAAPinRPxkInLvYf9Gstf4BtmMo8Q9Rbd4cvONkkVkV8upVjZazLopcjKVi+bfNHUnJU2S+tGj1NEkPk6SzI/dSUWTebG1auxOGprST9soxg1URdM6D03letxOCpp8dmp6fpwmMcsfj1N9ZdcbvYqmNGmS8teB4SdVb/gqmow5niTe3vsfr+sT4qZ7waqjSUxcFFn/W+abA7jvLFw6mo7zZuCeSIpw8qjS638raRr8MPuwp4Xr6kipbno5JXWmlOKm9GBb2/XFRnqbfJyfm+xObZOs3ffJT9zGXoovttLUdFyOyvCnmPIqyebnb5+mptCxDU0721G2y5eqptDxnh5P43m36TylFDVJvAqDX3jje0XWLuN2qmlpErf/Xo2cLwea7L7dUktTum0HX+1WQ012G66R1DSlxXnsb8NJ9TVSE6WlyS+iHzouRc2zJSVN4p5HJNV392FjFU2mGpUUnpfpaJLi75qTQnQ0tQ/DRqivkXQ0ffzd0troaPqckFRPKQ1N7pBMcXAKmh7v/dPjvft8wHfU9Y3SLT8lmPVvCcLDyhvce9gAAAAAAAAAAAAAAAAAAAAAAOBevgAdGBs8jYfPtgAAAABJRU5ErkJggg==', max_length=800),
        ),
    ]
